# Generated by Django 4.0.2 on 2025-01-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('specialist', '0001_initial'),
        ('shop', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='specialist.doctor'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='favorite_doctor',
            field=models.ManyToManyField(blank=True, related_name='fav_dock', to='specialist.Doctor'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='favorite_medicine',
            field=models.ManyToManyField(blank=True, related_name='fav_med', to='shop.Medicine'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='specialist_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='worker', to='specialist.doctor'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
