# Generated by Django 4.0.2 on 2026-01-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register account'), ('activate', 'Activate account'), ('reset_password', 'Reset password')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smscode',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
