# Generated by Django 4.0.2 on 2026-01-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_smscode_purpose_alter_smscode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
