# Generated by Django 4.0.2 on 2026-01-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_usermodel_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register account'), ('reset_password', 'Reset password')], max_length=30),
        ),
    ]
