# Generated by Django 4.0.2 on 2026-01-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_ordermodel_shipping_address_and_more'),
        ('account', '0005_alter_smscode_purpose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
