# Generated by Django 4.0.2 on 2026-01-25 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_remove_ordermodel_shipping_address_and_more'),
        ('client', '0002_clientaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='shop.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='medicinelike',
            index=models.Index(fields=['user'], name='client_medi_user_id_3a4b40_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinelike',
            index=models.Index(fields=['medicine'], name='client_medi_medicin_8ab8f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicinelike',
            unique_together={('user', 'medicine')},
        ),
    ]
