# Generated by Django 4.0.2 on 2026-02-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_medicinelike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
