# Generated by Django 4.0.2 on 2026-01-19 13:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('specialist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notification/')),
                ('foreign_id', models.CharField(blank=True, max_length=255, null=True)),
                ('push_time', models.DateTimeField(default=datetime.datetime(2026, 1, 19, 18, 14, 57, 624417))),
                ('type', models.SmallIntegerField(choices=[(1, 'medicines'), (2, 'doctors')], db_index=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StoriesContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='news/stories/')),
                ('content_uz', models.FileField(blank=True, upload_to='news/stories/')),
                ('content_ru', models.FileField(blank=True, upload_to='news/stories/')),
                ('content_en', models.FileField(blank=True, upload_to='news/stories/')),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_name_uz', models.CharField(max_length=50, null=True)),
                ('tag_name_ru', models.CharField(max_length=50, null=True)),
                ('tag_name_en', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('title_uz', models.TextField(blank=True, default='')),
                ('title_ru', models.TextField(blank=True, default='')),
                ('title_en', models.TextField(blank=True, default='')),
                ('icon', models.ImageField(null=True, upload_to='news/stories/icon')),
                ('contents', models.ManyToManyField(to='news.StoriesContent')),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/2026-1-1/')),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='news.tagsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine/advertising/')),
                ('image_uz', models.ImageField(blank=True, null=True, upload_to='medicine/advertising/')),
                ('image_ru', models.ImageField(blank=True, null=True, upload_to='medicine/advertising/')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='medicine/advertising/')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('text', models.TextField()),
                ('text_uz', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'medicines'), (2, 'doctors'), (3, 'banner')], db_index=True, default=1)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='special_news_doc', to='specialist.doctor')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='special_news_med', to='shop.medicine')),
            ],
        ),
    ]
