# Generated by Django 4.0.2 on 2026-01-20 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='push_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 20, 11, 6, 23, 963862)),
        ),
    ]
