# Generated by Django 4.0.2 on 2026-01-21 11:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_notification_push_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoriesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='news/stories/2026-1/')),
            ],
        ),
        migrations.RemoveField(
            model_name='stories',
            name='contents',
        ),
        migrations.AlterField(
            model_name='notification',
            name='push_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 16, 43, 41, 410095)),
        ),
        migrations.DeleteModel(
            name='StoriesContent',
        ),
        migrations.AddField(
            model_name='storiesimage',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.stories'),
        ),
    ]
