# Generated by Django 4.0.2 on 2026-01-21 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_storiesimage_remove_stories_contents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='push_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 19, 0, 3, 827580)),
        ),
    ]
