# Generated by Django 4.0.2 on 2026-01-24 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_notification_push_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='push_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 24, 16, 45, 7, 809195)),
        ),
    ]
