# Generated by Django 4.0.2 on 2026-01-31 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_alter_notification_push_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='push_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 31, 16, 24, 22, 570205)),
        ),
    ]
