# Generated by Django 4.0.2 on 2026-02-02 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_alter_notification_push_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/2026-2-2/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='push_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 2, 11, 35, 14, 207683)),
        ),
        migrations.AlterField(
            model_name='storiesimage',
            name='image',
            field=models.FileField(upload_to='news/stories/2026-2/'),
        ),
    ]
