# Generated by Django 4.0.2 on 2026-02-03 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_alter_newsmodel_image_alter_notification_push_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='push_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 3, 11, 24, 52, 250119)),
        ),
    ]
