# Generated by Django 4.0.2 on 2026-02-06 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0038_alter_notification_push_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='push_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 6, 15, 46, 58, 519740)),
        ),
    ]
