# Generated by Django 4.0.2 on 2026-01-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamviewer',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
