# Generated by Django 4.0.2 on 2026-01-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message/files/2026-1-1/'),
        ),
        migrations.AlterField(
            model_name='filemessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message/images/2026-1-1/'),
        ),
    ]
