# Generated by Django 4.0.2 on 2026-01-27 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_messageattachment_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_room_id_5feac5_idx',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='is_active',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_message_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_message_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('1:1', 'One to One'), ('group', 'Group')], default='1:1', max_length=10),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='file_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='chat_thumbnails/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(upload_to='chat_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['-updated_at'], name='chat_chatro_updated_fe8347_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_type'], name='chat_chatro_room_ty_0e9cce_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-created_at'], name='chat_messag_room_id_edc775_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='chat_messag_sender__62c9f9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='chat_messag_is_read_872c73_idx'),
        ),
    ]
