# Generated by Django 4.0.2 on 2026-01-28 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0003_alter_chatroom_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('audio', 'Audio Call'), ('video', 'Video Call')], max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('answered', 'Answered'), ('ended', 'Ended'), ('missed', 'Missed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('livekit_room_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('ringing_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('recording_enabled', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_received', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='chat.chatroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('initiated', 'Call Initiated'), ('ringing', 'Ringing'), ('answered', 'Answered'), ('ended', 'Ended'), ('missed', 'Missed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('quality_changed', 'Quality Changed'), ('reconnecting', 'Reconnecting')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='call.call')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='callevent',
            index=models.Index(fields=['call', 'timestamp'], name='call_callev_call_id_bc61a2_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['caller', '-created_at'], name='call_call_caller__7d7e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['receiver', '-created_at'], name='call_call_receive_4a2b12_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['status', '-created_at'], name='call_call_status_be1926_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['livekit_room_name'], name='call_call_livekit_77b45d_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['call_type', '-created_at'], name='call_call_call_ty_0b7cbe_idx'),
        ),
    ]
