# Generated by Django 4.0.2 on 2026-01-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callevent',
            name='event_type',
            field=models.CharField(choices=[('initiated', 'Call Initiated'), ('ringing', 'Ringing'), ('answered', 'Answered'), ('ended', 'Ended'), ('missed', 'Missed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('quality_changed', 'Quality Changed'), ('reconnecting', 'Reconnecting')], max_length=20),
        ),
    ]
