# Generated by Django 4.0.2 on 2025-01-16 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='defaults/60111.jpg', upload_to='doctor/')),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('full_name_uz', models.CharField(max_length=255, null=True)),
                ('full_name_ru', models.CharField(max_length=255, null=True)),
                ('full_name_en', models.CharField(max_length=255, null=True)),
                ('review', models.IntegerField(default=0)),
                ('experience', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='types/')),
            ],
        ),
        migrations.CreateModel(
            name='RateDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=4)),
                ('feedback', models.SmallIntegerField(choices=[(1, 'Not Bad'), (2, 'Love it'), (3, 'Nice Work'), (4, 'Awesome')], default=1)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='specialist.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='type_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='specialist.typedoctor'),
        ),
        migrations.CreateModel(
            name='AdviceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='specialist.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor/advertising/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='specialist.doctor')),
            ],
        ),
    ]
