# Generated by Django 4.0.2 on 2026-01-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorInvite',
        ),
    ]
