# Generated by Django 4.0.2 on 2026-01-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0002_delete_doctorinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma', models.FileField(upload_to='doctor_docs/diplomas/')),
                ('passport', models.FileField(blank=True, null=True, upload_to='doctor_docs/passports/')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('license_expire_date', models.DateField(blank=True, null=True)),
                ('workplace', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='specialist.doctor')),
            ],
        ),
    ]
