# Generated by Django 4.0.2 on 2026-01-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0003_doctorverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorverification',
            name='passport',
        ),
    ]
