# Generated by Django 4.0.2 on 2026-01-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0006_remove_doctor_review_doctor_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorrating',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='doctorview',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='doctorrating',
            constraint=models.UniqueConstraint(fields=('doctor', 'user'), name='unique_doctor_user_rating'),
        ),
        migrations.AddConstraint(
            model_name='doctorview',
            constraint=models.UniqueConstraint(fields=('doctor', 'user'), name='unique_doctor_view'),
        ),
    ]
