# Generated by Django 4.0.2 on 2026-02-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0007_alter_doctorrating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_price',
            field=models.DecimalField(decimal_places=2, default=50000, help_text='Consultation price in UZS (Set by admin)', max_digits=10),
        ),
    ]
