# Generated by Django 4.0.2 on 2026-01-19 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('paymeuz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=1, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'active'), (2, 'done')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PicturesMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_pictures/2026-1-1/')),
            ],
        ),
        migrations.CreateModel(
            name='TypeMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='types/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='types/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'Оплата при доставке'), (2, 'Кредитная карта'), (3, 'Прямой банковский перевод')], default=2)),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(1, 'В ожидании'), (2, 'Ошибка'), (3, 'Завершено'), (4, 'Отменен'), (5, 'Истёк'), (6, 'Возвращен')], default=1)),
                ('delivery_status', models.PositiveSmallIntegerField(choices=[(1, 'В ожидании'), (2, 'На доставке'), (3, 'Доставлен'), (4, 'Возвращен')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart_products', models.ManyToManyField(to='shop.CartModel')),
                ('credit_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='paymeuz.card')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.deliveryman')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.deliveryaddress')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine/')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('order_count', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('review', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('cost', models.IntegerField(null=True)),
                ('discount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_inn', models.CharField(blank=True, max_length=255, null=True)),
                ('product_ikpu', models.CharField(blank=True, max_length=255, null=True)),
                ('product_package_code', models.CharField(blank=True, max_length=255, null=True)),
                ('content_uz', models.TextField(null=True)),
                ('content_ru', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('features_uz', models.TextField(null=True)),
                ('features_ru', models.TextField(null=True)),
                ('features_en', models.TextField(null=True)),
                ('certificates_uz', models.TextField(null=True)),
                ('certificates_ru', models.TextField(null=True)),
                ('certificates_en', models.TextField(null=True)),
                ('application_uz', models.TextField(null=True)),
                ('application_ru', models.TextField(null=True)),
                ('application_en', models.TextField(null=True)),
                ('contraindications_uz', models.TextField(null=True)),
                ('contraindications_ru', models.TextField(null=True)),
                ('contraindications_en', models.TextField(null=True)),
                ('pictures', models.ManyToManyField(blank=True, to='shop.PicturesMedicine')),
                ('type_medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.typemedicine')),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('feedback_client', 'Mijozlar izohi'), ('feedback_product', 'Mahsulot izohi'), ('product_instruction', "Mahsulot qo'llanmasi")], default='feedback_client', max_length=75)),
                ('category', models.CharField(blank=True, choices=[('feedback_client', 'Mijozlar izohi'), ('feedback_celebrities', 'Mashxurlar izohi'), ('feedback_specialists', 'Mutahassislar izohi')], default='feedback_client', max_length=75)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feedbacks', to='shop.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.medicine'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
