# Generated by Django 4.0.2 on 2026-01-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturesmedicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_pictures/2026-1-1/'),
        ),
    ]
