# Generated by Django 4.0.2 on 2026-01-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='pictures',
        ),
        migrations.AddField(
            model_name='picturesmedicine',
            name='medicine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='shop.medicine'),
            preserve_default=False,
        ),
    ]
