# Generated by Django 4.0.2 on 2026-01-23 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_remove_medicine_pictures_picturesmedicine_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='shop.medicine'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cartmodel',
            unique_together={('user', 'product', 'status')},
        ),
        migrations.AddIndex(
            model_name='cartmodel',
            index=models.Index(fields=['user', 'status'], name='shop_cartmo_user_id_8d9e18_idx'),
        ),
    ]
