# Generated by Django 4.0.2 on 2026-01-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cartmodel_created_at_alter_cartmodel_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
