# Generated by Django 4.0.2 on 2026-01-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_medicine_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='shipping_address',
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'active'), (2, 'done'), (3, 'Deleted')], default=1),
        ),
    ]
