# Generated by Django 4.0.2 on 2026-02-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_medicine_name_alter_medicine_name_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
