# Generated by Django 4.0.2 on 2026-01-19 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeTransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='transaction id')),
                ('request_id', models.IntegerField(verbose_name='request id')),
                ('order_id', models.IntegerField(verbose_name='order id')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('state', models.IntegerField(blank=True, null=True, verbose_name='state')),
                ('status', models.CharField(choices=[('processing', 'processing'), ('success', 'success'), ('failed', 'failed'), ('canceled', 'canceled')], default='processing', max_length=55, verbose_name='status')),
                ('_type', models.CharField(choices=[('payment', 'payment'), ('referral', 'referral')], default='PAYMENT', max_length=55, verbose_name='type')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('perform_time', models.BigIntegerField(default=0, verbose_name='perform time')),
                ('cancel_time', models.BigIntegerField(default=0, verbose_name='cancel time')),
                ('cancel_reason', models.IntegerField(blank=True, null=True, verbose_name='cancel reason')),
            ],
            options={
                'verbose_name': 'payme transaction',
                'verbose_name_plural': 'payme transactions',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('expire', models.CharField(max_length=5)),
                ('token', models.TextField()),
                ('recurrent', models.BooleanField()),
                ('verify', models.BooleanField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
