# Generated by Django 4.0.2 on 2025-01-16 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialist', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommentMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rate', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comments_med', to='shop.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('rate', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comments_doc', to='specialist.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='commentmedicine',
            constraint=models.UniqueConstraint(fields=('medicine', 'user'), name='rate_med'),
        ),
        migrations.AddConstraint(
            model_name='commentdoctor',
            constraint=models.UniqueConstraint(fields=('doctor', 'user'), name='rate_doc'),
        ),
    ]
