# Generated by Django 4.0.2 on 2026-02-05 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_alter_chatroom_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(db_index=True)),
                ('requested_time', models.TimeField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consultation_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalAvailabilityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'global_availability_templates',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slot', to='consultation.consultationrequest')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_slots', to='consultation.globalavailabilitytemplate')),
            ],
            options={
                'db_table': 'doctor_availability',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='availability_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='consultation.doctoravailability'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='globalavailabilitytemplate',
            index=models.Index(fields=['date', 'is_active'], name='global_avai_date_613cc5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='globalavailabilitytemplate',
            unique_together={('date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='doctoravailability',
            index=models.Index(fields=['doctor', 'date', 'is_available'], name='doctor_avai_doctor__9ba0ff_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoravailability',
            index=models.Index(fields=['template', 'is_available'], name='doctor_avai_templat_f38e9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['doctor', 'requested_date', 'status'], name='consultatio_doctor__441640_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['client', 'status'], name='consultatio_client__3f3228_idx'),
        ),
    ]
