# Generated by Django 4.0.2 on 2026-02-03 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Hamkor nomi')),
                ('api_key', models.CharField(max_length=100, unique=True, verbose_name='API Key')),
                ('api_secret', models.CharField(max_length=255, verbose_name='API Secret (hashed)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('rate_limit_per_minute', models.IntegerField(default=60, verbose_name="Minutiga so'rovlar soni")),
                ('total_requests', models.IntegerField(default=0, verbose_name="Jami so'rovlar")),
                ('total_users_created', models.IntegerField(default=0, verbose_name='Yaratilgan userlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='partner_auth.partner')),
            ],
            options={
                'verbose_name': "Hamkor so'rovi",
                'verbose_name_plural': "Hamkor so'rovlari",
                'db_table': 'partner_requests',
            },
        ),
        migrations.AddIndex(
            model_name='partnerrequest',
            index=models.Index(fields=['-created_at'], name='partner_req_created_242796_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerrequest',
            index=models.Index(fields=['partner', '-created_at'], name='partner_req_partner_d5cc3a_idx'),
        ),
    ]
